const DOCS = [
  {id:'doc01',number:'RD-001 · Observatório do Véu',classif:'restrito',classifLabel:'Restrito',title:'A Natureza da Quinta Dimensão',subtitle:'Relatório Introdutório',desc:'Compilação dos primeiros estudos sobre a 5ª Dimensão.',origin:'Observatório do Véu',date:'Ano 112 P.V.',password:'veuberto',content:`<div class="doc-seal-line">Observatório do Véu</div><div class="doc-section-title">I. Definição Operacional</div><p class="doc-body-text">A <strong>5ª Dimensão</strong> é a camada da realidade imediatamente adjacente à dimensão física...</p>`},
  {id:'doc02',number:'CD-007 · Departamento Histórico',classif:'confidencial',classifLabel:'Confidencial',title:'A Queda de Aethryon',subtitle:'Relatos de Sobreviventes',desc:'Transcrições dos únicos sobreviventes documentados.',origin:'Departamento Histórico',date:'Anos 3–11 P.V.',password:'aethryon',content:`<div class="doc-seal-line">Testemunhos Históricos</div><div class="doc-section-title">Testemunho I</div><p class="doc-body-text">"Não foi uma explosão. O ar abriu-se como um tecido rasgado..."</p>`},
  {id:'doc03',number:'RI-014 · Inquisidores Arcanos',classif:'confidencial',classifLabel:'Confidencial',title:'Operação Véu Costurado',subtitle:'Desarticulação do Culto do Olho Aberto',desc:'Relatório da operação que infiltrou o culto dimensional.',origin:'Inquisidores Arcanos',date:'Anos 1041–1043 P.V.',password:'olhoaberto',content:`<div class="doc-seal-line">Inquisidores Arcanos</div><p class="doc-body-text">A entidade <em>Vardhal</em> foi selada em contenção de Nível 3.</p>`},
  {id:'doc04',number:'CE-002 · Conclave Interno',classif:'maximo-sigilo',classifLabel:'Máximo Sigilo',title:'O Problema Demográfico',subtitle:'Memorando Interno',desc:'Declínio no número de praticantes.',origin:'Conclave Interno',date:'Ano 1044 P.V.',password:'conclave1044',content:`<div class="doc-seal-line">Conclave Interno</div><p class="doc-body-text">Nos últimos 42 anos, o número de indivíduos com capacidade dimensional caiu 31%...</p>`},
  {id:'doc05',number:'PD-033 · Pesquisa Dimensional',classif:'restrito',classifLabel:'Restrito',title:'Classificação de Entidades',subtitle:'Manual de Campo',desc:'Manual para classificação de entidades da 5ª Dimensão.',origin:'Observatório do Véu',date:'Ano 1039 P.V.',password:'entidades',content:`<div class="doc-seal-line">Manual de Campo</div><p class="doc-body-text">Nunca negociar com entidades de Classe III sem autorização do Conclave.</p>`},
  {id:'doc06',number:'AI-088 · Aurethia',classif:'maximo-sigilo',classifLabel:'Máximo Sigilo',title:'Experimentos Ilegais',subtitle:'Relatório Câmaras Brancas',desc:'Experimentos em humanos com potencial dimensional.',origin:'Inteligência Interna',date:'Ano 1043 P.V.',password:'aurethia43',content:`<div class="doc-seal-line">Inteligência Interna</div><p class="doc-body-text">Por sete votos a dois: NÃO confrontar Aurethia neste momento.</p>`},
  {id:'doc07',number:"TH-011 · Thal'Myrion",classif:'restrito',classifLabel:'Restrito',title:'O Declínio Élfico',subtitle:"Missão a Thal'Myrion",desc:'Documentação do declínio da raça élfica.',origin:'Relações Externas',date:'Ano 1038 P.V.',password:'thalmyrion',content:`<div class="doc-seal-line">Relações Externas</div><p class="doc-body-text">Thal'Myrion está a morrer. Vimos cinco crianças em quarenta e dois dias.</p>`},
  {id:'doc08',number:"VZ-003 · Vhal'Zarak",classif:'maximo-sigilo',classifLabel:'Máximo Sigilo',title:'O Que Há no Nexus Umbral',subtitle:'Expedição de 1041',desc:"O único relatório de uma expedição ao Nexus Umbral.",origin:"Expedição Especial",date:'Ano 1041 P.V.',password:'nexusumbral',content:`<div class="doc-seal-line">Vhal'Zarak</div><p class="doc-body-text">A recomendação é clara: Nenhuma expedição adicional deve ser autorizada.</p>`},
  {id:'doc09',number:'IG-019 · Relações com a Igreja',classif:'confidencial',classifLabel:'Confidencial',title:'A Profecia do Selador',subtitle:'Versões Divergentes',desc:'Análise das versões da profecia do Quinto Véu.',origin:'Relações com a Igreja',date:'Ano 1040 P.V.',password:'selador7',content:`<div class="doc-seal-line">Análise Teológica</div><p class="doc-body-text">"O Selador não fechará o Quinto Véu porque é justo. Fechará porque não terá escolha."</p>`},
  {id:'doc10',number:"KD-005 · Khar'Duran",classif:'restrito',classifLabel:'Restrito',title:'A Muralha Está Cedendo',subtitle:"Avaliação Militar",desc:"Capacidade da Grande Muralha de Duran-Khal.",origin:"Ligação Militar",date:'Ano 1044 P.V.',password:'muralha44',content:`<div class="doc-seal-line">Khar'Duran</div><p class="doc-body-text">Estimativa de vida útil sem reparo estrutural massivo: 15 a 40 anos.</p>`}
];

const BEASTS = [
  {name:'Goblin',icon:'👺',type:'Humanoide Pequeno',rarity:'comum',cr:'1/4',hp:'7',ac:'15',speed:'30ft',desc:'Vivem em grupos nos esgotos e ruínas de Porto Varion.',lore:'Chamados de "filhos do lixo" na Baixa Varion.'},
  {name:'Esqueleto',icon:'💀',type:'Morto-vivo Médio',rarity:'comum',cr:'1/4',hp:'13',ac:'13',speed:'30ft',desc:'Restos animados por magia residual.',lore:'Não precisam de necromante. Basta energia dimensional.'},
  {name:'Zumbi',icon:'🧟',type:'Morto-vivo Médio',rarity:'comum',cr:'1/4',hp:'22',ac:'8',speed:'20ft',desc:'Lentos mas resistentes. Sinal de uso ilegal de magia.',lore:'Onde há um, há uma fonte próxima.'},
  {name:'Lobo',icon:'🐺',type:'Besta Média',rarity:'comum',cr:'1/4',hp:'11',ac:'13',speed:'40ft',desc:'Predadores com olhos pálidos quando corrompidos.',lore:'Registados na rota da Liga Mercante.'},
  {name:'Kobold',icon:'🦎',type:'Humanoide Pequeno',rarity:'comum',cr:'1/8',hp:'5',ac:'12',speed:'30ft',desc:'Engenhosos e covardes em grupo.',lore:'Usam aparelhos de medição roubados do Sínodo.'},
  {name:'Bandido',icon:'🗡️',type:'Humanoide Médio',rarity:'comum',cr:'1/8',hp:'11',ac:'12',speed:'30ft',desc:'Criminosos da Baixa Varion.',lore:'A guilda dos "Véus Rasgados" recruta ex-agentes.'},
  {name:'Rato Gigante',icon:'🐀',type:'Besta Pequena',rarity:'comum',cr:'1/8',hp:'7',ac:'12',speed:'30ft',desc:'Infestam esgotos do porto.',lore:'Alguns nascem com duas caudas no Bairro do Véu.'},
  {name:'Cultista',icon:'🕯️',type:'Humanoide Médio',rarity:'comum',cr:'1/8',hp:'9',ac:'12',speed:'30ft',desc:'Seguidores fanatizados de entidades dimensionais.',lore:'Surgem novos grupos após a Operação Véu Costurado.'},
  {name:'Guarda',icon:'🛡️',type:'Humanoide Médio',rarity:'comum',cr:'1/8',hp:'11',ac:'16',speed:'30ft',desc:'Guardas leais a quem paga.',lore:'O Sínodo triplicou os guardas no Cais das Nações.'},
  {name:'Gnoll',icon:'🐗',type:'Humanoide Médio',rarity:'comum',cr:'1/2',hp:'22',ac:'15',speed:'30ft',desc:'Predadores de aspeto canino.',lore:'Capturados com caixotes nobres de Aurethia.'},
  {name:'Hobgoblin',icon:'⚔️',type:'Humanoide Médio',rarity:'comum',cr:'1/2',hp:'11',ac:'18',speed:'30ft',desc:'Mercenários disciplinados.',lore:'Contratados pela Liga Mercante.'},
  {name:'Bugbear',icon:'🐻',type:'Humanoide Grande',rarity:'comum',cr:'1',hp:'27',ac:'16',speed:'40ft',desc:'Grandes, furtivos e brutais.',lore:'Trabalham como carregadores pesados no Cais.'},
  {name:'Ogre',icon:'👹',type:'Gigante Grande',rarity:'incomum',cr:'2',hp:'59',ac:'11',speed:'40ft',desc:'Força bruta descomunal.',lore:'Usados como seguranças no porto norte.'},
  {name:'Serpente Dimensional',icon:'🐍',type:'Monstrosity',rarity:'incomum',cr:'2',hp:'32',ac:'13',speed:'30ft',desc:'Translúcida, pode atravessar paredes.',lore:'Originária das fissuras do Bairro do Véu.'},
  {name:'Sombra Dimensional',icon:'🌑',type:'Não-morto Médio',rarity:'incomum',cr:'3',hp:'16',ac:'12',speed:'40ft',desc:'Drena força física ao toque.',lore:'Luz solar as desfaz. Aparecem em Aethryon.'},
  {name:'Basilisco',icon:'🦎',type:'Monstrosity Média',rarity:'incomum',cr:'3',hp:'52',ac:'15',speed:'20ft',desc:'Olhar petrificante. Territorial.',lore:'Vive nas galerias sob o Distrito Académico.'},
  {name:'Harpia',icon:'🦅',type:'Monstrosity Média',rarity:'incomum',cr:'1',hp:'38',ac:'11',speed:'20ft',desc:'Canto hipnótico.',lore:'Nidificam no estaleiro velho de Varion.'},
  {name:'Eco de Aethryon',icon:'👤',type:'Aberração Média',rarity:'raro',cr:'5',hp:'67',ac:'14',speed:'30ft',desc:'Loop temporal residual.',lore:'Pode ter surgido de um sobrevivente em colapso.'},
  {name:'Guardião do Véu',icon:'🌀',type:'Construto Grande',rarity:'raro',cr:'8',hp:'142',ac:'17',speed:'30ft',desc:'Armadura de pedra com núcleo da 5ª Dimensão.',lore:'O terceiro no subsolo não responde há 40 anos.'},
  {name:'Fragmento de Vardhal',icon:'👁️',type:'Aberração Grande',rarity:'raro',cr:'9',hp:'178',ac:'16',speed:'0ft',desc:'Inteligente e manipulador.',lore:'Lê memórias pelo contacto visual.'}
];

const GLOSSARY = [
  {id: 'lore01', term: 'O Quinto Véu', category: 'Dimensão', desc: 'A camada da realidade adjacente ao plano físico. É de onde a magia emana e onde o Tratado de Vhal\'Torin mantém vigilância constante.', restricted: false},
  {id: 'lore02', term: 'Tratado de Vhal\'Torin', category: 'História', desc: 'O acordo global que encerrou a Guerra do Véu, proibindo o uso livre da magia e estabelecendo o Sínodo como órgão regulador.', restricted: false},
  {id: 'lore03', term: 'Resina Etérea', category: 'Substância', desc: 'Líquido roxo pulsante que amplia a percepção dimensional em não-treinados. Altamente viciante e perigoso.', restricted: false},
  {id: 'lore04', term: 'A Cicatriz de Vhal\'Zarak', category: 'Localização', desc: 'Ponto onde a realidade foi permanentemente rasgada durante o colapso dimensional.', restricted: true, password: 'cicatrizaberta'},
  {id: 'lore05', term: 'Investigador de Véu', category: 'Patente', desc: 'Nível avançado de autoridade conferido a Agentes de Vínculo.', restricted: true, password: 'bronze7'}
];