const DOCS = [
  {id:'doc01',number:'RD-001 · Observatório do Véu',classif:'restrito',classifLabel:'Restrito',title:'A Natureza da Quinta Dimensão',subtitle:'Relatório Introdutório',desc:'Compilação dos primeiros estudos formais sobre a 5ª Dimensão.',origin:'Observatório do Véu',date:'Ano 112 P.V.',password:'veuberto',content:`<div class="doc-seal-line">Observatório do Véu</div><div class="doc-section-title">I. Definição Operacional</div><p class="doc-body-text">A <strong>5ª Dimensão</strong> é a camada da realidade adjacente à dimensão física...</p>`},
  {id:'doc02',number:'CD-007 · Departamento Histórico',classif:'confidencial',classifLabel:'Confidencial',title:'A Queda de Aethryon',subtitle:'Relatos de Sobreviventes',desc:'Transcrições dos únicos sobreviventes documentados.',origin:'Departamento Histórico',date:'Anos 3–11 P.V.',password:'aethryon',content:`<div class="doc-seal-line">Testemunhos Históricos</div><div class="doc-section-title">Testemunho I</div><p class="doc-body-text">"Não foi uma explosão. O ar abriu-se como um tecido rasgado de dentro para fora..."</p>`},
  {id:'doc03',number:'RI-014 · Inquisidores Arcanos',classif:'confidencial',classifLabel:'Confidencial',title:'Operação Véu Costurado',subtitle:'Culto do Olho Aberto',desc:'Desarticulação da rede de contrabando dimensional.',origin:'Inquisidores Arcanos',date:'Anos 1041–1043 P.V.',password:'olhoaberto',content:`<div class="doc-seal-line">Inquisidores Arcanos</div><p class="doc-body-text">A entidade <em>Vardhal</em> foi selada em contenção de Nível 3 no subsolo.</p>`},
  {id:'doc04',number:'CE-002 · Conclave Interno',classif:'maximo-sigilo',classifLabel:'Máximo Sigilo',title:'O Problema Demográfico',subtitle:'Memorando Interno',desc:'Declínio no número de praticantes de magia.',origin:'Conclave Interno',date:'Ano 1044 P.V.',password:'conclave1044',content:`<div class="doc-seal-line">Conclave Interno</div><p class="doc-body-text">Nos últimos 42 anos, o número de indivíduos com capacidade caiu 31%...</p>`},
  {id:'doc05',number:'PD-033 · Pesquisa Dimensional',classif:'restrito',classifLabel:'Restrito',title:'Classificação de Entidades',subtitle:'Manual de Campo',desc:'Manual para identificação de entidades dimensionais.',origin:'Observatório do Véu',date:'Ano 1039 P.V.',password:'entidades',content:`<div class="doc-seal-line">Manual de Campo</div><p class="doc-body-text">Nunca negociar com entidades de Classe III sem autorização do Conclave.</p>`},
  {id:'doc06',number:'AI-088 · Inteligência',classif:'maximo-sigilo',classifLabel:'Máximo Sigilo',title:'Experiências Ilegais',subtitle:'Câmaras Brancas',desc:'Pesquisa arcana não autorizada em Aurethia.',origin:'Inteligência Interna',date:'Ano 1043 P.V.',password:'aurethia43',content:`<div class="doc-seal-line">Inteligência Interna</div><p class="doc-body-text">Por sete votos a dois: NÃO confrontar Aurethia neste momento.</p>`},
  {id:'doc07',number:"TH-011 · Thal'Myrion",classif:'restrito',classifLabel:'Restrito',title:'O Declínio Élfico',subtitle:"Missão Diplomática",desc:'Relatório sobre a extinção progressiva da raça élfica.',origin:'Relações Externas',date:'Ano 1038 P.V.',password:'thalmyrion',content:`<div class="doc-seal-line">Relações Externas</div><p class="doc-body-text">Thal'Myrion está a morrer. Vimos cinco crianças em quarenta e dois dias.</p>`},
  {id:'doc08',number:"VZ-003 · Vhal'Zarak",classif:'maximo-sigilo',classifLabel:'Máximo Sigilo',title:'Nexus Umbral',subtitle:'Expedição de 1041',desc:"O único relatório de expedição que retornou.",origin:"Expedição Especial",date:'Ano 1041 P.V.',password:'nexusumbral',content:`<div class="doc-seal-line">Vhal'Zarak</div><p class="doc-body-text">A recomendação é clara: Nenhuma expedição adicional deve ser autorizada.</p>`},
  {id:'doc09',number:'IG-019 · Igreja',classif:'confidencial',classifLabel:'Confidencial',title:'Profecia do Selador',subtitle:'Análise Teológica',desc:'Análise das versões da profecia do Quinto Véu.',origin:'Relações com a Igreja',date:'Ano 1040 P.V.',password:'selador7',content:`<div class="doc-seal-line">Análise Teológica</div><p class="doc-body-text">"O Selador não fechará o Quinto Véu porque é justo. Fechará porque não terá escolha."</p>`},
  {id:'doc10',number:"KD-005 · Khar'Duran",classif:'restrito',classifLabel:'Restrito',title:'Muralha Cedendo',subtitle:"Avaliação Militar",desc:"Capacidade da Grande Muralha de Duran-Khal.",origin:"Ligação Militar",date:'Ano 1044 P.V.',password:'muralha44',content:`<div class="doc-seal-line">Khar'Duran</div><p class="doc-body-text">Estimativa de vida útil sem reparo estrutural massivo: 15 a 40 anos.</p>`}
];

const BEASTS = [
  {name:'Goblin',icon:'👺',type:'Humanoide Pequeno',rarity:'comum',cr:'1/4',hp:'7',ac:'15',speed:'30ft',desc:'Vivem nos esgotos e ruínas de Porto Varion.',lore:'Chamados de "filhos do lixo" na Baixa Varion.'},
  {name:'Esqueleto',icon:'💀',type:'Morto-vivo Médio',rarity:'comum',cr:'1/4',hp:'13',ac:'13',speed:'30ft',desc:'Restos animados por magia residual.',lore:'Não precisam de necromante. Basta energia dimensional.'},
  {name:'Zumbi',icon:'🧟',type:'Morto-vivo Médio',rarity:'comum',cr:'1/4',hp:'22',ac:'8',speed:'20ft',desc:'Lentos, mas muito resistentes.',lore:'Onde há um, há uso de magia perto.'},
  {name:'Lobo',icon:'🐺',type:'Besta Média',rarity:'comum',cr:'1/4',hp:'11',ac:'13',speed:'40ft',desc:'Predadores com olhos pálidos quando corrompidos.',lore:'Alcateias avistadas na ferrovia.'},
  {name:'Kobold',icon:'🦎',type:'Humanoide Pequeno',rarity:'comum',cr:'1/8',hp:'5',ac:'12',speed:'30ft',desc:'Engenhosos e covardes em grupo.',lore:'Usam aparelhos roubados do Sínodo.'},
  {name:'Bandido',icon:'🗡️',type:'Humanoide Médio',rarity:'comum',cr:'1/8',hp:'11',ac:'12',speed:'30ft',desc:'Criminosos armados organizados.',lore:'Contratados por contrabandistas de Resina Etérea.'},
  {name:'Rato Gigante',icon:'🐀',type:'Besta Pequena',rarity:'comum',cr:'1/8',hp:'7',ac:'12',speed:'30ft',desc:'Infestam as zonas portuárias.',lore:'Mutações frequentes perto do Bairro do Véu.'},
  {name:'Cultista',icon:'🕯️',type:'Humanoide Médio',rarity:'comum',cr:'1/8',hp:'9',ac:'12',speed:'30ft',desc:'Seguidores fanatizados do Véu.',lore:'Uso excessivo de rituais proibidos.'},
  {name:'Guarda',icon:'🛡️',type:'Humanoide Médio',rarity:'comum',cr:'1/8',hp:'11',ac:'16',speed:'30ft',desc:'Guardas leais a quem paga.',lore:'Muito presentes no Cais das Nações.'},
  {name:'Gnoll',icon:'🐗',type:'Humanoide Médio',rarity:'comum',cr:'1/2',hp:'22',ac:'15',speed:'30ft',desc:'Predadores caóticos de aspeto canino.',lore:'Agressividade aumentada em áreas com anomalias.'},
  {name:'Hobgoblin',icon:'⚔️',type:'Humanoide Médio',rarity:'comum',cr:'1/2',hp:'11',ac:'18',speed:'30ft',desc:'Mercenários táticos e cruéis.',lore:'Geralmente trabalham para a Liga Mercante.'},
  {name:'Bugbear',icon:'🐻',type:'Humanoide Grande',rarity:'comum',cr:'1',hp:'27',ac:'16',speed:'40ft',desc:'Extremamente furtivos para o tamanho que têm.',lore:'Trabalham pesado nos portos.'},
  {name:'Ogre',icon:'👹',type:'Gigante Grande',rarity:'incomum',cr:'2',hp:'59',ac:'11',speed:'40ft',desc:'Força bruta pura.',lore:'Dão bons guardas-costas para cargas ilegais.'},
  {name:'Serpente Dimensional',icon:'🐍',type:'Monstrosity',rarity:'incomum',cr:'2',hp:'32',ac:'13',speed:'30ft',desc:'Cobra translúcida flutuante.',lore:'Atravessa paredes físicas sem dificuldade.'},
  {name:'Sombra Dimensional',icon:'🌑',type:'Não-morto',rarity:'incomum',cr:'3',hp:'16',ac:'12',speed:'40ft',desc:'Drena energia com o toque.',lore:'Pode ser desfeita por luz solar forte.'},
  {name:'Basilisco',icon:'🦎',type:'Monstrosity Média',rarity:'incomum',cr:'3',hp:'52',ac:'15',speed:'20ft',desc:'Transforma a vítima em pedra.',lore:'Vive sob o Distrito Académico do Sínodo.'},
  {name:'Harpia',icon:'🦅',type:'Monstrosity Média',rarity:'incomum',cr:'1',hp:'38',ac:'11',speed:'20ft',desc:'Canto que hipnotiza humanos.',lore:'Nidificam no estaleiro velho de Varion.'},
  {name:'Eco de Aethryon',icon:'👤',type:'Aberração Média',rarity:'raro',cr:'5',hp:'67',ac:'14',speed:'30ft',desc:'Fantasma preso num loop temporal.',lore:'Um reflexo deixado pela Grande Guerra.'},
  {name:'Guardião do Véu',icon:'🌀',type:'Construto Grande',rarity:'raro',cr:'8',hp:'142',ac:'17',speed:'30ft',desc:'Golem ancestral de pedra e magia.',lore:'Protege as áreas mais restritas do Sínodo.'},
  {name:'Fragmento de Vardhal',icon:'👁️',type:'Aberração Grande',rarity:'raro',cr:'9',hp:'178',ac:'16',speed:'0ft',desc:'Extremamente inteligente e letal.',lore:'Lê a mente através do contacto visual.'}
];

const GLOSSARY = [
  {id:'lore01', term:'O Quinto Véu', category:'Dimensão', desc:'A camada adjacente ao plano físico de onde a magia emana.', restricted:false},
  {id:'lore02', term:'Tratado de Vhal\'Torin', category:'História', desc:'O acordo global que encerrou a Guerra do Véu, proibindo magia livre.', restricted:false},
  {id:'lore03', term:'Resina Etérea', category:'Substância', desc:'Droga que amplia a perceção dimensional de forma ilegal e letal.', restricted:false},
  {id:'lore04', term:'A Cicatriz de Vhal\'Zarak', category:'Local', desc:'O ponto focal do colapso dimensional antigo.', restricted:true, password:'cicatrizaberta'},
  {id:'lore05', term:'Investigador de Véu', category:'Patente', desc:'Nível de autoridade máximo dos Agentes de Vínculo veteranos.', restricted:true, password:'bronze7'}
];